name: Deploy GO Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: iroghamajoseph
          password: Toyotapicnic1.
      - name: Build docker image
        run: docker build -t iroghamajoseph/asset_upload .
      - name: Publish image to docker hub
        run: docker push iroghamajoseph/asset_upload:latest

  # deploy:
  #   needs: build
  #   runs-on: self-hosted

  #   steps:
  #     - name: Pull Image From Docker Hub
  #       run: echo joseph@2024 | sudo -S docker pull iroghamajoseph/asset_upload:latest
  #     - name: Delete Existing Container
  #       run: echo joseph@2024 | sudo -S docker rm -f asset_upload
  #     - name: Run docker container
  #       run: echo joseph@2024 | sudo -S docker run  --env-file /home/rendcore/asset-upload/.env -d -p 8080:8080 --name asset_upload iroghamajoseph/asset_upload:latest
